' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Controller-Klasse

interface Promise<T>

package @nestjs/graphql {
  class "@Resolver" as Resolver
  hide Resolver circle

  class "@UseGuards" as UseGuards
  hide UseGuards circle

  class "@UseInterceptors" as UseInterceptors
  hide UseInterceptors circle

  class "@Mutation" as Mutation
  hide Mutation circle

  class "@Args" as Args
  hide Args circle
}

package nest-keycloak-connect {
  class AuthGuard

  class "@Roles" as Roles
  hide Roles circle
}

package serie #DDDDDD {
  package entity #FFFFFF {
    class Serie <<entity>>
  }

  package service #FFFFFF {
    class SerieWriteService << control >>
  }

  class "type SerieDTO = Omit<Serie, 'covers' | 'aktualisiert' | 'erzeugt'" as SerieDTO
  hide SerieDTO circle

    interface IdInput {
        id: number
    }

  class SerieMutationResolver << control >> << @Resolver() >> << @UseGuards() >> << @UseInterceptors() >> {
    + @Mutation() @Roles() async create(@Args() serieDTO: SerieDTO): Promise<number>
    + @Mutation() @Roles() async update(@Args() serieDTO: SerieDTO): Promise<number>
    + @Mutation() @Roles() async delete(@Args() id: IdInput): Promise<boolean>
  }

  SerieMutationResolver o-down-> "1" SerieWriteService : service

  SerieMutationResolver ..> Serie
  SerieMutationResolver ..> SerieDTO
  SerieMutationResolver ..> IdInput
  SerieDTO .up.> Serie
  SerieMutationResolver ..> Promise
  SerieMutationResolver ..> Resolver

  SerieMutationResolver .up.> AuthGuard
  SerieMutationResolver .up.> Roles

  SerieDTO .[hidden].> Promise
  SerieDTO .[hidden].> Resolver
}

hide empty members

footer (c) Engin Dagdas

@enduml
